--- Rendering the build Gradle reads.
---
--- The whole point of this file is in two lines of what it writes: the source
--- sets point back at the real tree, and every dependency is an absolute path
--- into daukle's artifact cache. So there is NO `repositories {}` block and
--- Gradle resolves nothing. Resolution is daukle/maven's, which is the end goal
--- rather than a convenience.

local build_file = {}

--[[ The derived directory is build/daukle/gradle/, so the project root is three
     levels up. It is load bearing and fails SILENTLY when wrong: with the
     sourceSets block removed, Gradle resolves src/main/java against the project
     directory, finds nothing, compiles nothing and exits 0 on `classes`. That
     is why the tests assert on compiled output and never on this text. ]]
local ROOT = "../../.."

local function groovy_string(text)
  return "'" .. text:gsub("\\", "/"):gsub("'", "\\'") .. "'"
end

local function src_dirs(paths)
  if #paths == 0 then return "[]" end
  local rendered = {}
  for index = 1, #paths do
    rendered[index] = "new File(file(" .. groovy_string(ROOT) .. "), " .. groovy_string(paths[index])
                      .. ")"
  end
  return "[" .. table.concat(rendered, ", ") .. "]"
end

local function file_list(paths, indent)
  local rendered = {}
  for index = 1, #paths do
    rendered[index] = indent .. groovy_string(paths[index])
  end
  return table.concat(rendered, ",\n")
end

local function source_set(name, java_dirs, resource_dirs)
  return "  " .. name .. " {\n"
         .. "    java      { srcDirs = " .. src_dirs(java_dirs) .. " }\n"
         .. "    resources { srcDirs = " .. src_dirs(resource_dirs) .. " }\n"
         .. "  }"
end

--- @param layout  { main = {java, resources}, test = {java, resources} }
--- @param jars    { compile = {path...}, test = {path...} }
--- @param options { release, main }
function build_file.render(layout, jars, options)
  local lines = {
    "// Generated by daukle/gradle. Do not edit: daukle.toml is yours, this is not.",
    "// Every dependency below is a path into daukle's artifact cache, pinned by",
    "// sha256 before it got there, which is why this build declares no repository.",
    "",
    "plugins { id 'java' }",
    "",
    "sourceSets {",
    source_set("main", layout.main.java, layout.main.resources),
    source_set("test", layout.test.java, layout.test.resources),
    "}",
    "",
    "dependencies {",
  }
  if #jars.compile > 0 then
    lines[#lines + 1] = "  implementation files(\n" .. file_list(jars.compile, "    ") .. "\n  )"
  end
  if #jars.test > 0 then
    lines[#lines + 1] = "  testImplementation files(\n" .. file_list(jars.test, "    ") .. "\n  )"
  end
  lines[#lines + 1] = "}"
  lines[#lines + 1] = ""

  if options.release ~= nil then
    lines[#lines + 1] = "java {"
    lines[#lines + 1] = "  sourceCompatibility = JavaVersion.toVersion("
                        .. groovy_string(options.release) .. ")"
    lines[#lines + 1] = "  targetCompatibility = JavaVersion.toVersion("
                        .. groovy_string(options.release) .. ")"
    lines[#lines + 1] = "}"
    lines[#lines + 1] = ""
  end

  --[[ Pinned rather than inherited, and this is not housekeeping: java-utils'
       own build carries a comment recording that Gradle 8.11.1 read its sources
       as Cp1252 on Windows where 7.6.4 read them as UTF-8, so an unpinned
       encoding makes the compiled bytes a property of whichever build ran. It
       matters more in a generated file than in a hand-written one, because the
       user cannot see this one. ]]
  lines[#lines + 1] = "tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }"
  lines[#lines + 1] = ""
  lines[#lines + 1] = "test { useJUnitPlatform() }"

  if options.main ~= nil then
    lines[#lines + 1] = ""
    lines[#lines + 1] = "tasks.register('daukleRun', JavaExec) {"
    lines[#lines + 1] = "  classpath = sourceSets.main.runtimeClasspath"
    lines[#lines + 1] = "  mainClass = " .. groovy_string(options.main)
    lines[#lines + 1] = "}"
  end

  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

--- Without this Gradle names the project after its directory, which would be
--- "gradle".
function build_file.settings(name)
  return "// Generated by daukle/gradle. Do not edit.\n"
         .. "rootProject.name = " .. groovy_string(name) .. "\n"
end

return build_file
